services:
  campaign-db:
    container_name: campaign.postgres
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: campaign
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always
    networks:
      - campaign_network

  campaign-pgadmin:
    container_name: campaign.pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      campaign-db:
        condition: service_healthy
    restart: always
    networks:
      - campaign_network

  workspace:
    container_name: campaign.workspace
    build:
      context: .
      dockerfile: build/workspace/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      campaign-db:
        condition: service_healthy
    ports:
      - '3000:3000'
    restart: always
    command: ['npm', 'run', 'start:dev']
    networks:
      - campaign_network

volumes:
  pgdata:

networks:
  campaign_network:
    driver: bridge
